// Must stay in sync with LOCATIONS in backend/app/game_logic.py
export const LOCATIONS = [
  "Airplane",
  "Bank",
  "Beach",
  "Casino",
  "Circus Tent",
  "Corporate Party",
  "Day Spa",
  "Embassy",
  "Hospital",
  "Hotel",
  "Military Base",
  "Movie Studio",
  "Ocean Liner",
  "Passenger Train",
  "Pirate Ship",
  "Police Station",
  "Restaurant",
  "School",
  "Space Station",
  "Submarine",
  "Supermarket",
  "Theater",
];
