// Must stay in sync with LOCATIONS in backend/app/game_logic.py
export const LOCATIONS = [
  "Airplane",
  "Airport",
  "Bank",
  "Beach",
  "Beetle",
  "Bookstore",
  "Burger",
  "Candy",
  "Casino",
  "Chef",
  "Chocolate",
  "Cinema",
  "Circus Tent",
  "Coffee",
  "Cook",
  "Corporate Party",
  "Cushion",
  "Day Spa",
  "Doctor",
  "Dolphin",
  "Earphones",
  "Elephant",
  "Embassy",
  "Firefighter",
  "Flight Attendant",
  "Gelato",
  "Headphones",
  "Hospital",
  "Hotel",
  "Ice Cream",
  "Lemonade",
  "Library",
  "Lion",
  "Military Base",
  "Mirror",
  "Movie Studio",
  "Nurse",
  "Ocean Liner",
  "Passenger Train",
  "Penguin",
  "Pharmacy",
  "Pillow",
  "Pilot",
  "Pizza",
  "Polar Bear",
  "Police Officer",
  "Police Station",
  "Professor",
  "Raincoat",
  "Restaurant",
  "Rhinoceros",
  "Sashimi",
  "School",
  "Space Station",
  "Spider",
  "Submarine",
  "Supermarket",
  "Sushi",
  "Swimming Pool",
  "Tea",
  "Teacher",
  "Theater",
  "Tiger",
  "Toothbrush",
  "Toothpaste",
  "Train Station",
  "Umbrella",
  "Whale",
  "Window",
];
